### PR TITLE
Update to version 314

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
Huh?

> Failed to download sources: module cockpit-client: Wrong sha256 checksum for cockpit-314.tar.xz, expected "436172717fe536a3064c1d01afd810eca5f47af8e094327c65d2f29a1fa9f01a", was "a92955e73ec3d9569db74675268baaec963c07f6db12c1a64bb57a25b1eb0f6a"

And it's right:
```
$ curl -L https://github.com/cockpit-project/cockpit/releases/download/314/cockpit-314.tar.xz | sha256sum -
a92955e73ec3d9569db74675268baaec963c07f6db12c1a64bb57a25b1eb0f6a
```

@allisonkarlitskaya some bug in our PR creation script?

**Comment by allisonkarlitskaya** [comment]
> @allisonkarlitskaya some bug in our PR creation script?

Nope.  It was caused by the fact that the release went out twice.

This workflow run successfully uploaded the release and pushed the flatpak branch `314`: https://github.com/cockpit-project/cockpit/actions/runs/8451494766

This workflow run, the following day, replaced the tarball but failed to push the flatpak branch (leaving the old one in place, with a different checksum): https://github.com/cockpit-project/cockpit/actions/runs/8465003228

It also failed to publish the guide.

We might change the release workflow to force-push over top of existing commits to deal with the re-release-the-same-version thing...

**Comment by mvollmer** [comment]
> We might change the release workflow to force-push over top of existing commits to deal with the re-release-the-same-version thing...

Or let's not ever restart a failed release with the same tag?

**Comment by martinpitt** [comment]
I pushed the correct SHA.

**Comment by martinpitt** [comment]
I tested localhost, remote with bridge, and remote with beiboot.

**Pull request merged**
