### PR TITLE
vendor patch: Bump GNOME release to 45

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
Upstream: https://github.com/cockpit-project/cockpit/pull/19366

### CODE REVIEW

**Comment by allisonkarlitskaya** [comment]
The bot got stuck.  Let's try again.

**Comment by allisonkarlitskaya** [comment]
Started [test build 67408](https://buildbot.flathub.org/#/builders/6/builds/67408)

**Comment by allisonkarlitskaya** [comment]
More infra fail...

**Comment by allisonkarlitskaya** [comment]
bot, build

**Review by garrett — APPROVED** [review]
Looks good! Thanks! :+1:

**Comment by allisonkarlitskaya** [comment]
I tested it as well for a little while and everything looks fine.

**Pull request merged**
